### ISSUE TITLE
Добавить проверку входящих сообщений для предотвращения XSS-атак

### ISSUE THREAD

**Issue by lilolemo** [Alendorff/Chat-PO11#2]
Т.к. входящие сообщения добавляются в виде html кода, это большой потенциал для эксплуатации XSS-уязвимостей. Необходимо исключить возможность передать в сообщении потенциально опасные html-теги.

**Comment by maksnester** [comment]
Для предотвращения XSS добавил дополнительную валидацию на всевозможное получение данных от пользователя (создание комнаты, логин) + добавил модуль [sanitizer](https://github.com/theSmaw/Caja-HTML-Sanitizer) для того чтобы экранировать любой html код.  
Как следствие, теперь любые html теги приходят в виде тегов, и если захочется дополнительного форматирования, тут придётся что-то допилить.
