### ISSUE TITLE
не работает

### ISSUE THREAD

**Issue by tresdosdos** [Alendorff/Chat-PO11#21]
сделал клон, пофиксил баг с bson, запускаю
![image](https://user-images.githubusercontent.com/36292581/39034351-bdb3bb12-447e-11e8-8d45-ebd5d528500a.png)

Захожу на страницу, а там бесконечный лоад и страница недоступна
![image](https://user-images.githubusercontent.com/36292581/39034374-cf329e6c-447e-11e8-8cdb-fa126b2971bd.png)

В связи с этим два вопроса:
1. как пофиксить?
2. как запустить по локальной сети?
Спасибо

**Comment by tresdosdos** [comment]
при закрытии сервера
![image](https://user-images.githubusercontent.com/36292581/39034883-b52be170-4480-11e8-820f-83db92e69428.png)

**Comment by faaswdepkhab** [comment]
Здравствуйте!

Проект разрабатывался небольшой командной. Я курировал работу команды,
непосредственным кодированием не занимался. Кодированием занимался Нестернко
Максим (ник на github.com - Alendorff)

С уважением, Федосеев Андрей.

  20.04.2018, 16:56:02 пользователь Vitaliy Diachuk (notifications@github.com)
  написал:


  при закрытии сервера
  image

**Comment by tresdosdos** [comment]
@faaswdepkhab я поэтому ему и пишу, очень нужен этот проект в рабочем состоянии)

**Comment by maksnester** [comment]
@faaswdepkhab Приветствую, Андрей Анатольевич. Вы просто в списке тех, кто следит за проектом ) Если не хотите больше никогда получать таких email'ов, то зайдите на страницу репозитория, например сюда https://github.com/Alendorff/Chat-PO11/watchers и нажмите Unwatch (в правом верхнем углу).


@tresdosdos теперь к issue. Я не веду этот "проект", он был в своё время просто сдан в качестве лабы. Прошло несколько лет с тех пор и что-то могло поменяться и перестать работать. Как минимум вышло много новых версий для nodejs и mongodb. Я уже даже не возьмусь сказать какие версии были на момент создания этого репозитория. Можно попробовать поискать в сети или на официальных сайтах архивы версий и примерно подобрать актуальные версии для того времени (кстати в readme есть ссылка на скринкаст, возможно там можно подсмотреть какие были версии тогда актуальны)

Сейчас пробую установить по своей инструкции:
* куча сообщений от npm, что всё устарело, какие-то ошибки компиляции чего-то от node_gyp, всё плохо короч (но вроде пакеты поставились)
* bower надо запускать из папки public/vendor, а не public
* тоже попал на проблему `Error: Cannot find module 'mongodb/node_modules/bson'` ~поскольку мне безразлично сопровождение этого проекта и я не планирую тратить время на то чтобы сделать фикс этого,~ иду в mongodb/node_modules, делаю там `npm i` и возвращаюсь обратно в папку с проектом.
* при запуске вижу что всё равно есть проблемы с bson но якобы запускаться не мешает. Вообще там явно какие-то серьёзные проблемы при сборке всяких нативных плагинов. Разбираться с ними как-то не хочется.
* воспроизводится заявленная в issue проблема - "не работает"

Резюмируя: оно сдохло )) 

Что делать? Ну, как я сказал, можно ещё попробовать воссоздать окружение тех лет, поставив старые версии npm, node, mongodb. Но это вполне может и не помочь со сборкой пакетов. А может и помочь. Кто знает... 

А по-хорошему, я бы советовал написать своё. Оно и для обучения лучше будет и более актуально. Да и более интересно, чем пытаться воссоздать окружение прошлых лет, исправляя непонятные ошибки, до которых никому уже нет дела.

Вообще, забавно, что на этот репозиторий периодически кто-то набредает и пытается использовать. Возможно, я даже как-нибудь перепишу его на новый лад. Чтоб было стильно-модно-молодёжно. Но это будет не сегодня и не завтра и вообще когда-нибудь... Или нет ¯\_(ツ)_/¯

**Comment by faaswdepkhab** [comment]
Здравствуйте!

Проект создавался в качестве контрольной работы по учебной дисциплине. Занимался
организацией кодирования Нестеренко Максим. Проект несколько лет поддерживается.
Привожу слова Максима:

" ...

Сейчас пробую установить по своей инструкции:

  * куча сообщений от npm, что всё устарело, какие-то ошибки компиляции чего-то
    от node_gyp, всё плохо короч (но вроде пакеты поставились)

  * bower надо запускать из папки public/vendor, а не public

  * тоже попал на проблему Error: Cannot find module 'mongodb/node_modules/bson,
    иду в mongodb/node_modules, делаю там npm i и возвращаюсь обратно в папку с
    проектом.

  * при запуске вижу что всё равно есть проблемы с bson но якобы запускаться не
    мешает. Вообще там явно какие-то серьёзные проблемы при сборке всяких
    нативных плагинов. Разбираться с ними как-то не хочется.

  * воспроизводится заявленная в issue проблема - "не работает"

Резюмируя: оно сдохло ))

... "

Суммируя всё вышесказанное, можно посоветовать следующее:

1. Попробовать другой проект

2. Переписать этот проект, используя новый инструментарий

С уважением, Андрей Федосеев.

  20.04.2018, 20:16:17 пользователь Vitaliy Diachuk (notifications@github.com)
  написал:


  @faaswdepkhab я поэтому ему и пишу, очень нужен этот проект в рабочем
  состоянии)

**Comment by faaswdepkhab** [comment]
Здравствуй, Максим!

Для меня тоже было сюрпризом, что на нашу подделку обратили внимание :-) Как у
тебя дела? Чем занимаешься? Судя по анкете тебя унесло аж до Калининграда... Как
там житиё-бытиё? Общаешься с кем-нибудь из своих бывших одногруппников?

С уважением, Андрей Федосеев.


  21.04.2018, 2:17:57 пользователь Nesterenko Maxim (notifications@github.com)
  написал:


  @faaswdepkhab Приветствую, Андрей Анатольевич. Вы просто в списке тех, кто
  следит за проектом ) Если не хотите больше никогда получать таких email'ов,
  то зайдите на страницу репозитория, например сюда
  https://github.com/Alendorff/Chat-PO11/watchers и нажмите Unwatch (в правом
  верхнем углу).

  @tresdosdos теперь к issue. Я не веду этот "проект", он был в своё время
  просто сдан в качестве лабы. Прошло несколько лет с тех пор и что-то могло
  поменяться и перестать работать. Как минимум вышло много новых версий для
  nodejs и mongodb. Я уже даже не возьмусь сказать какие версии были на момент
  создания этого репозитория. Можно попробовать поискать в сети или на
  официальных сайтах архивы версий и примерно подобрать актуальные версии для
  того времени (кстати в readme есть ссылка на скринкаст, возможно там можно
  подсмотреть какие были версии тогда актуальны)

  Сейчас пробую установить по своей инструкции:

    * куча сообщений от npm, что всё устарело, какие-то ошибки компиляции
      чего-то от node_gyp, всё плохо короч (но вроде пакеты поставились)

    * bower надо запускать из папки public/vendor, а не public

    * тоже попал на проблему Error: Cannot find module
      'mongodb/node_modules/bson' иду в mongodb/node_modules, делаю там npm i и
      возвращаюсь обратно в папку с проектом.

    * при запуске вижу что всё равно есть проблемы с bson но якобы запускаться
      не мешает. Вообще там явно какие-то серьёзные проблемы при сборке всяких
      нативных плагинов. Разбираться с ними как-то не хочется.

    * воспроизводится заявленная в issue проблема - "не работает"

  Резюмируя: оно сдохло ))

  Что делать? Ну, как я сказал, можно ещё попробовать воссоздать окружение тех
  лет, поставив старые версии npm, node, mongodb. Но это вполне может и не
  помочь со сборкой пакетов. А может и помочь. Кто знает...

  А по-хорошему, я бы советовал написать своё. Оно и для обучения лучше будет и
  более актуально. Да и более интересно, чем пытаться воссоздать окружение
  прошлых лет, исправляя непонятные ошибки, до которых никому уже нет дела.

  Вообще, забавно, что на этот репозиторий периодически кто-то набредает и
  пытается использовать. Возможно, я даже как-нибудь перепишу его на новый лад.
  Чтоб было стильно-модно-молодёжно. Но это будет не сегодня и не завтра и
  вообще когда-нибудь... Или нет ¯_(ツ)_/¯

**Comment by maksnester** [comment]
@faaswdepkhab Я Вам ответил на email faa1976@rambler.ru возможно email уже не актуален?
Вы просто всё это время в issue на гитхабе пишите, отвечая в почте )
